# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: David CSS Blog
url: http://docs.mscss.wang/
feed: /atom.xml
author_info: <a href="http://docs.mscss.wang/">David</a>

myblog:
  gavatar: images/2.jpg
  gpname: David
  linkedin: https://www.linkedin.com/in/%E5%92%8C%E9%98%B3-%E9%83%91-417549a3/
  github: https://github.com/mscss
  email: mailto:zhy391884651@live.com
  coverimgs: []
  postbgimg: []

categories: [python, books]

theme: jekyll-theme-architect